version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "Cyb3r-Jak3"
    commit-message:
      prefix: "Action Update"
    reviewers:
      - "Cyb3r-Jak3"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "Cyb3r-Jak3"
    commit-message:
      prefix: "GoMod update"
    reviewers:
      - "Cyb3r-Jak3"