version: "2"
run:
  modules-download-mode: readonly
output:
  formats:
    text:
      path: stderr
linters:
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - goconst
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - misspell
    - nilerr
    - prealloc
    - reassign
    - revive
    - staticcheck
    - unconvert
    - usetesting
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: exclude-dirs-use-default
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
