# $schema: https://golangci-lint.run/jsonschema/golangci.jsonschema.json

run:

  modules-download-mode: readonly

issues:
  exclude: exclude-dirs-use-default

linters:
  enable:
    - staticcheck
    - dupl
    - govet
    - goconst
    - usetesting
    - ineffassign
    - bodyclose
    - gosec
    - prealloc
    - unused
    - gofmt
    - revive
    - stylecheck
    - whitespace
    - goprintffuncname
    - gosimple
    - gocyclo
    - copyloopvar
    - goimports
    - misspell
    - godot
    - reassign
    - unconvert
    - nilerr
    - govet

output:
  formats:
    - format: colored-line-number
      path: stderr
    - format: github-actions
      path: stdout
