version: 2
before:
  hooks:
    - go mod tidy
    - cp ../../LICENSE .
    - cp ../../README.md .
    - cp ../../bash_completion .

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - '386'
      - s390x
      - ppc64le
    binary: cloudflare-utils
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}'
      - -extldflags "-static"


archives:
  - format: tar.xz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Version }}-snapshot-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

signs:
  - artifacts: all
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

sboms:
  - artifacts: archive

chocolateys:
  - title: "Cloudflare Utils"
    authors: "Cyb3r-Jak3"
    project_url: "https://cloudflare-utils.cyberjake.xyz/"
    docs_url: "https://cloudflare-utils.cyberjake.xyz/"
    license_url: "https://github.com/Cyb3r-Jak3/cloudflare-utils/blob/main/LICENSE"
    summary: "Community created utilities for Cloudflare"
    release_notes: "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/tag/{{ .Tag }}"
    tags: "cloudflare"
    bug_tracker_url: "https://github.com/Cyb3r-Jak3/cloudflare-utils/issues"
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
    copyright: "2023-2024 Cyb3r-Jak3"
    package_source_url: "https://github.com/Cyb3r-Jak3/cloudflare-utils"
    icon_url: "https://cloudflare-utils.cyberjake.xyz/assets/images/logo.png"
    description: &description |
      Community created utilities for Cloudflare such as:
      
      - Deleting all records in a zone
      - Deleting all records in a zone except for a list of records
      - Deleting all Pages deployments for a branch
      - Deleting all Pages deployments for project
      - Deleting all Pages deployments before or after a time
      
      Cloudflare and the Cloudflare logo are trademarks and/or registered trademarks of Cloudflare, Inc. in the United States and other jurisdictions.

nfpms:
  -
    package_name: cloudflare-utils
    vendor: Cyb3rJak3
    homepage: https://cloudflare-utils.cyberjake.xyz/
    maintainer: Cyb3rJak3 <git@cyberjake.xyz>
    description: *description
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    provides:
      - cloudflare-utils
    section: default
    priority: extra
    # Changelog YAML file, see: https://github.com/goreleaser/chglog
    #
    # You can use goreleaser/chglog to create the changelog for your project,
    # pass that changelog yaml file to GoReleaser,
    # and it should in turn setup it accordingly for the given available
    # formats (deb and rpm at the moment).
    #
    # Experimental.
    # Since: v1.11
#    changelog: ./foo.yml
    contents:
      - src: LICENSE
        dst: /usr/share/licenses/{{ .ProjectName }}/LICENSE.md
      - src: README.md
        dst: /usr/share/doc/{{ .ProjectName }}/README.md
      - src: bash_completion
        dst: /etc/bash_completion.d/{{ .ProjectName }}

blobs:
  - provider: s3
    region: auto
    endpoint: https://8be772befd147a8df540aae0fa15c047.r2.cloudflarestorage.com
    bucket: public-files

release:
  draft: true

brew:
  - name: cloudflare-utils
    description: *description
    license: Apache 2.0
    homepage: "https://cloudflare-utils.cyberjake.xyz/"
    repository:
      owner: Cyb3r-Jak3
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

