before:
  hooks:
    - go mod tidy
    - cp ../../LICENSE .

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    binary: cloudflare-utils
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: tar.xz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Version }}-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

dockers:
  - image_templates:
      - "cyberjake/cloudflare-utils:{{ .Tag }}-amd64"
      - "ghcr.io/cyb3r-jak3/cloudflare-utils:{{ .Tag }}-amd64"
    dockerfile: ../../dist.Dockerfile
    use: docker
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .CommitTimestamp }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.maintainer=Cyb3r Jak3 git@cyberjake.xyz"
      - "--platform=linux/amd64"
  - image_templates:
      - "cyberjake/cloudflare-utils:{{ .Tag }}-arm64"
      - "ghcr.io/cyb3r-jak3/cloudflare-utils:{{ .Tag }}-arm64"
    dockerfile: ../../dist.Dockerfile
    goarch: arm64
    use: docker
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .CommitTimestamp }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.maintainer=Cyb3r Jak3 git@cyberjake.xyz"

docker_manifests:
  - name_template: "cyberjake/cloudflare-utils:{{ .Tag }}"
    image_templates:
      - "cyberjake/cloudflare-utils:{{ .Tag }}-amd64"
      - "cyberjake/cloudflare-utils:{{ .Tag }}-arm64"

  - name_template: "cyberjake/cloudflare-utils:latest"
    image_templates:
      - "cyberjake/cloudflare-utils:{{ .Tag }}-amd64"
      - "cyberjake/cloudflare-utils:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/cyb3r-jak3/cloudflare-utils:{{ .Tag }}"
    image_templates:
      - "ghcr.io/cyb3r-jak3/cloudflare-utils:{{ .Tag }}-amd64"
      - "ghcr.io/cyb3r-jak3/cloudflare-utils:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/cyb3r-jak3/cloudflare-utils:latest"
    image_templates:
      - "ghcr.io/cyb3r-jak3/cloudflare-utils:{{ .Tag }}-amd64"
      - "ghcr.io/cyb3r-jak3/cloudflare-utils:{{ .Tag }}-arm64"

chocolateys:
  - title: "Cloudflare utils"
    authors: "Cyb3r-Jak3"
    project_url: "https://cloudflare-utils.cyberjake.xyz/"
    license_url: "https://github.com/Cyb3r-Jak3/cloudflare-utils/blob/main/LICENSE"
    summary: "Community created utilities for Cloudflare"
    release_notes: "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/tag/{{ .Tag }}"
    tags: "cloudflare"
    bug_tracker_url: "https://github.com/Cyb3r-Jak3/cloudflare-utils/issues"
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
    description: |
      {{ .ProjectName }} installer package.
      Community created utilities for Cloudflare such as:
      - deleting all records in a zone
      - deleting all records in a zone except for a list of records
      - deleting all Pages deployments for a branch



release:
  draft: true