before:
  hooks:
    - go mod tidy
    - cp ../../LICENSE .

builds:
  - env:
      - CGO_ENABLED=0
    flags:
    - -trimpath
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - '386'
      - s390x
      - ppc64le
    binary: cloudflare-utils
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}'
      - -extldflags "-static"


archives:
  - format: tar.xz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Version }}-snapshot-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

signs:
  - artifacts: all
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

chocolateys:
  - title: "Cloudflare Utils"
    authors: "Cyb3r-Jak3"
    project_url: "https://cloudflare-utils.cyberjake.xyz/"
    docs_url: "https://cloudflare-utils.cyberjake.xyz/"
    license_url: "https://github.com/Cyb3r-Jak3/cloudflare-utils/blob/main/LICENSE"
    summary: "Community created utilities for Cloudflare"
    release_notes: "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/tag/{{ .Tag }}"
    tags: "cloudflare"
    bug_tracker_url: "https://github.com/Cyb3r-Jak3/cloudflare-utils/issues"
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
    copyright: "2023 Cyb3r-Jak3"
    package_source_url: "https://github.com/Cyb3r-Jak3/cloudflare-utils"
    icon_url: "https://cloudflare-utils.cyberjake.xyz/assets/images/logo.png"
    description: |
      {{ .ProjectName }} installer package.
      Community created utilities for Cloudflare such as:
      
      - Deleting all records in a zone
      - Deleting all records in a zone except for a list of records
      - Deleting all Pages deployments for a branch
      - Deleting all Pages deployments for project
      - Deleting all Pages deployments based on time
      
      Cloudflare and the Cloudflare logo are trademarks and/or registered trademarks of Cloudflare, Inc. in the United States and other jurisdictions.

nfpms:
  -
    package_name: cloudflare-utils

    # Your app's vendor.
    vendor: Cyb3rJak3

    # Your app's homepage.
    homepage: https://cloudflare-utils.cyberjake.xyz/

    # Your app's maintainer (probably you).
    maintainer: Cyb3rJak3 <git@cyberjake.xyz>

    # Your app's description.
    description: |-
      Community created utilities for Cloudflare such as:
      
      - Deleting all records in a zone
      - Deleting all records in a zone except for a list of records
      - Deleting all Pages deployments for a branch
      - Deleting all Pages deployments for project
      
      Cloudflare and the Cloudflare logo are trademarks and/or registered trademarks of Cloudflare, Inc. in the United States and other jurisdictions.

    license: Apache 2.0

    formats:
      - apk
      - deb
      - rpm

    provides:
      - cloudflare-utils

    section: default

    priority: extra

    # Changelog YAML file, see: https://github.com/goreleaser/chglog
    #
    # You can use goreleaser/chglog to create the changelog for your project,
    # pass that changelog yaml file to GoReleaser,
    # and it should in turn setup it accordingly for the given available
    # formats (deb and rpm at the moment).
    #
    # Experimental.
    # Since: v1.11
#    changelog: ./foo.yml
    contents:
      - src: LICENSE
        dst: /usr/share/licenses/{{ .ProjectName }}/LICENSE.md


release:
  draft: true