before:
  hooks:
    - go mod tidy
    - cp ../../LICENSE .

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - 386
      - s390x
      - ppc64le
    binary: cloudflare-utils
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: tar.xz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Version }}-snapshot-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

chocolateys:
  - title: "Cloudflare utils"
    authors: "Cyb3r-Jak3"
    project_url: "https://cloudflare-utils.cyberjake.xyz/"
    docs_url: "https://cloudflare-utils.cyberjake.xyz/"
    license_url: "https://github.com/Cyb3r-Jak3/cloudflare-utils/blob/main/LICENSE"
    summary: "Community created utilities for Cloudflare"
    release_notes: "https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/tag/{{ .Tag }}"
    tags: "cloudflare"
    bug_tracker_url: "https://github.com/Cyb3r-Jak3/cloudflare-utils/issues"
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
    copyright: "2023 Cyb3r-Jak3"
    package_source_url: "https://github.com/Cyb3r-Jak3/cloudflare-utils"
    icon_url: "https://cloudflare-utils.cyberjake.xyz/assets/images/logo.png"
    description: |
      {{ .ProjectName }} installer package.
      Community created utilities for Cloudflare such as:
      
      - Deleting all records in a zone
      - Deleting all records in a zone except for a list of records
      - Deleting all Pages deployments for a branch
      - Deleting all Pages deployments for project
      
      Cloudflare and the Cloudflare logo are trademarks and/or registered trademarks of Cloudflare, Inc. in the United States and other jurisdictions.

release:
  draft: true