name: Clear Cache on PR Close
on:
  pull_request:
    types: [ closed ]

jobs:
  clear-caches:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      actions: write
    steps:
      - name: Clear caches
        uses: theAngularGuy/clear-cache-of-pull-request@b72bb60cd2fa48c01695afdf0ca755b34b115429
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clear Page Deployments
        uses: Cyb3r-Jak3/actions-cloudflare-utils@v1
        if: ${{ github.event.pull_request.merged == true }}
        with:
          args: prune-deployments --project cloudflare-utils --branch ${{ github.event.pull_request.head.ref }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_CACHE_CLEANER }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}