name: released

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      -
        name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          vt_monitor: true
          monitor_path: /cyb3rjak3/cloudflare-utils
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          files: |
            .zip$